# Generated by Django 2.2.10 on 2020-09-24 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dreamreal',
        ),
    ]
