# Generated by Django 2.2.10 on 2020-09-29 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_pricehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SymbolList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'symbol_list',
            },
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='datetime',
            field=models.IntegerField(),
        ),
    ]
