# Generated by Django 2.2.10 on 2020-10-02 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_dailypricehistory_hourlypricehistory_monthlypricehistory_weeklypricehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'portfolio_list',
            },
        ),
        migrations.CreateModel(
            name='PortfolioSymbolList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('entry', models.FloatField()),
            ],
            options={
                'db_table': 'portfolio_symbol_list',
            },
        ),
    ]
